import type { NextPage } from 'next';
import Head from 'next/head';
import { usePhantom } from '@dobosmarton/phantom-hook';
import styles from '../styles/Home.module.css';

const Home: NextPage = () => {
  const { walletAddress, connectWallet, disconnectWallet } = usePhantom();

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Welcome to Web3!</h1>

        <p className={styles.description}>Get started by connecting your Phantom Wallet</p>

        {!walletAddress && (
          <a onClick={connectWallet} className={styles.card}>
            <p>Connect Phantom Wallet</p>
          </a>
        )}

        {walletAddress && (
          <>
            <p className={styles.address}>
              <strong>Wallett address</strong>: {walletAddress}
            </p>
            <a onClick={disconnectWallet} className={styles.card}>
              <p>Disconnect Phantom Wallet</p>
            </a>
          </>
        )}

        <div className={styles.grid}>
          <a href="https://solana.com/" className={styles.card}>
            <h2>Solana &rarr;</h2>
            <p>Find in-depth information about the Solana blockchain.</p>
          </a>

          <a href="https://phantom.app/" className={styles.card}>
            <h2>Phantom &rarr;</h2>
            <p>Learn about Phantom, which is an cool and modern crypto wallet!</p>
          </a>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by Marton Dobos
        </a>
      </footer>
    </div>
  );
};

export default Home;
